---
- name: install isc-dhcp-server
  sudo: yes
  apt: pkg=isc-dhcp-server state=installed
  tags: isc-dhcp-server

- name: Install dhcpd config
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf

- name: Copy dhcpd server config to default so it would run against an interface
  template: src=isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server

- name: Make sure isc-dhcp-server is not yet running service and not start on boot
  service: name=isc-dhcp-server enabled=no state=stopped
  become: true
