hostapd_conf:
  interface : 'wlan0'
  ssid : 'sanpentest'
  channel : '10'
  macaddr_acl : '0'
  auth_algs : '1'
  wpa : '2'
  hw_mode : 'g'
  wpa_passphrase : 'awesomepasswordhere'
  wpa_key_mgmt : 'WPA-PSK'
  wpa_pairwise : 'CCMP'
  rsn_pairwise : 'CCMP'
