---

- name: Check if grimd is installed
  become:true
  stat: path=/usr/sbin/grimd
  register: grimd_installed

- name: download
  become: true
  get_url:
    url: "https://github.com/looterz/grimd/releases/download/v1.0.5/grimd_linux_x64"
    dest: /usr/sbin/grimd
    owner: root
    group: root
    mode: 0755
  when: grimd_installed is false
