---
- name: install hostapd
  sudo: yes
  apt: pkg=hostapd state=installed force=yes
  tags: hostapd

- name: Copy hostapd config
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf

- name: Copy hostapd to default so service will work
  template: src=hostapd.j2 dest=/etc/default/hostapd

- name: Make sure hostapd is not yet running service and not start on boot
  service: name=hostapd enabled=no state=stopped
  become: true

# - name: Make sure hostapd starts
#   service: name=hostapd state=running enabled=yes
